name: Build
"on":
  workflow_call:
    inputs:
      MOZ_BUILD_DATE:
        required: false
        type: string
      PRE_RELEASE:
        required: false
        type: string
      TRIGGER_EVENT:
        description: Trigger event for the workflow
        required: true
        type: string
      TAG_VERSION:
        required: false
        type: string
    outputs:
      versiondisplay:
        description: Output display version
        value: "${{ jobs.build-windows-arm64.outputs.versionout }}"
env:
  MOZ_BUILD_DATE: "${{ inputs.MOZ_BUILD_DATE }}"
  PRE_RELEASE: "${{ inputs.PRE_RELEASE }}"
jobs:
  build-windows-arm64:
    name: Windows ARM64
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.head_ref }}-windows-arm64"
      cancel-in-progress: true
    env:
      MOZCONFIG: .mozconfig-aarch64-pc-windows-msvc
      WINEDEBUG: "-all"
      ARCH: aarch64-pc-windows-msvc
      CARGO_INCREMENTAL: "0"
      CARGO_TERM_COLOR: always
      SCCACHE_GHA_ENABLED: "true"
    outputs:
      versionout: "${{ steps.versionexport.outputs.version }}"
    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     remove-dotnet: 'true'
      #     remove-android: 'true'
      #     remove-haskell: 'true'
      #     remove-codeql: 'true'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "\U0001F4BF Build dependencies"
        run: |
          sudo apt update
          sudo apt install msitools
          rustup target add aarch64-pc-windows-msvc
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L "https://www.7-zip.org/a/7z2408-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
      - name: "\U0001F4E4 Checkout"
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: "\U0001F4E3 Override version_display.txt"
        if: ${{ inputs.TRIGGER_EVENT == 'workflow_dispatch' }}
        run: |
          if [[ -n "${{ inputs.TAG_VERSION }}" ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: "\U0001F4E3 Export VERSION_DISPLAY"
        id: versionexport
        run: echo "version=$(echo ${{ env.VERSION_DISPLAY }})" >> $GITHUB_OUTPUT
      - name: "\U0001F3D7 Build"
        run: |
          if [[ "${{ inputs.TRIGGER_EVENT }}" == 'workflow_dispatch' ]]; then
            if [[ "$PRE_RELEASE" == 'true' ]]; then
              export WFX_PRE_RELEASE=1
              echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
              echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
            else
              export WFX_RELEASE=1
              echo "Set WFX_RELEASE as ${WFX_RELEASE}"
              echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
            fi
          fi
          ./mach build
      - name: "\U0001F4E6 Package"
        if: ${{ inputs.TRIGGER_EVENT == 'workflow_dispatch' }}
        run: |
          ./mach package
          if [ -d "$PWD"/waterfox/browser/locales/en-GB ]; then
            ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW
          fi
      - name: "\U0001F199 Upload artifact"
        if: ${{ inputs.TRIGGER_EVENT == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64-${{ github.run_id }}
          path: |
            obj-${{ env.ARCH }}/dist/waterfox.zip
